
multipass: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype: false
  - removeXMLProcInst: false
  - removeComments: false
  - removeMetadata: true
  - removeXMLNS: true
  - removeEditorsNSData: true
  - cleanupAttrs: true
  - inlineStyles: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - cleanupIDs: true
  - prefixIds: true
  - removeRasterImages: true
  - removeUselessDefs: true
  - cleanupNumericValues:
      floatPrecision: 2
  - cleanupListOfValues: true
  - convertColors: true
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeViewBox: true
  - cleanupEnableBackground: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - convertShapeToPath: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: true
  - convertPathData: true
  - convertTransform: true
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - mergePaths: false
  - removeUnusedNS: true
  - sortAttrs: true
  - removeTitle: false
  - removeDesc: true
  - removeDimensions: true
  - removeAttrs: true
  - removeAttributesBySelector: true
  - removeElementsByAttr: true
  - addClassesToSVGElement: false
  - removeStyleElement: true
  - removeScriptElement: true
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: true
  - reusePaths: false

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
js2svg:
  pretty: true
  indent: '  '
